Repository civiform/cloud-deploy-infra, pull requests merged in 2024-11, with the labels that each got.

#411 Upgrade azure provider version
  cloud/azure/main.tf
Labels: enhancement

#415 Update azure env var AZURE_STORAGE_ACCOUNT_CONTAINER to AZURE_STORAGE_ACCOUNT_CONTAINER_NAME
  cloud/azure/modules/app/locals.tf
Labels: bug

#419 Create variable for email provider
  cloud/aws/templates/aws_oidc/variables.tf
  cloud/azure/templates/azure_saml_ses/variables.tf
  cloud/shared/variable_definitions.json
Labels: documentation

#423 Have Terraform create the public-files container for program card images for Azure deployments
  cloud/azure/modules/app/file-storage.tf
  cloud/azure/modules/app/locals.tf
Labels: enhancement
