Repository civiform/cloud-deploy-infra, pull requests merged in 2024-10, with the labels that each got.

#403 Allow an optional cert file to be specified that gets used by pip
  cloud/shared/bin/python_env_setup
  cloud/shared/bin/run
Labels: enhancement

#408 Add ability to skip provider registrations for the terraform azure provider.
  cloud/azure/main.tf
  cloud/azure/templates/azure_saml_ses/providers.tf
  cloud/azure/templates/azure_saml_ses/variable_definitions.json
  cloud/azure/templates/azure_saml_ses/variables.tf
Labels: bug, enhancement

#406 Create a docker image that can be used to deploy CIVIFORM to aws and azure
  .github/workflows/push_deployment_env_image.yaml
  cloud/aws/deployment/build-deployment
  cloud/aws/deployment/development.Dockerfile
  cloud/aws/deployment/library-scripts/docker-in-docker-debian.sh
Labels: enhancement

#409 Match dockerfile name to action name (deployment-env)
  .github/workflows/push_deployment_env_image.yaml
  cloud/aws/deployment/build-deployment
  cloud/aws/deployment/deployment-env.Dockerfile
Labels: bug
